version: 1
app:
  locale: ru-RU
  timezone: Europe/Moscow
  show_clock: false
  clock_format: HH:mm
parking:
  parser:
    server: http://195.239.135.49:8085
    path: /pgs/map_monitor/parking_free_public.jsp
    token: 73e80ac1be2e5c396833cfe479526df335f78e83e7dcbbb9
content:
  working_hours:
  - 'Ежедневно: 08:00–22:00'
  tariffs:
  - Первые 2 часа бесплатно
  - С 3-го часа — 50 рублей/час
  - После 22:00 — 500 рублей/ночь
media:
  ads_path: /data/ads
  carousel_seconds: 8
  allowed_extensions:
  - .jpg
  - .jpeg
  - .png
  - .webp
  - .gif
  - .mp4
  - .webm
  - .ogg
ui:
  settings_access:
    hidden_hotspot_enabled: true
  diagnostics:
    show_raw_yaml_preview: true
    show_parser_test: true
  blocks:
    show_working_hours: true
    show_free_spaces: true
    show_tariffs: true
    show_carousel: true
appearance:
  accent_color: '#ffffff'
  success_color: '#00ff33'
  warning_color: '#ff0000'
  danger_color: '#a81600'
  background_start: '#ff0505'
  background_end: '#0088ff'
operating_mode:
  manual_mode: normal
  schedule_enabled: true
  schedule_from: '10:51'
  schedule_to: '22:00'
  closed_text: Парковка не работает
